### ISSUE TITLE
about dictionary update？

### ISSUE THREAD

**Issue by xilinniao123** [tmu-nlp/DistantTermExtractor#1]
hi：
thanks for sharing thie project. 
i want to ask how to update seed dictionary? in the code i have not see any update,but in your paper  it maybe updated by false positive words?
so can you tell me how you update the seed dictionary?

**Comment by ryosukee** [comment]
thank you for your comments.
In my paper, i did not mention about updating seed dictionary (as far as i remember).
it means that i executed CRF only once in my experiments.

I'm so sorry, this project is too old to remember the detail of experiments. if you can point out the corresponding explanation in my paper, please show me. i may be able to answer more clearly.

**Comment by xilinniao123** [comment]
in the http://cl.sd.tmu.ac.jp/~miyazaki/publish/nlp2015_miyazaki_poster.pdf, 
i am not familiar with japannese,in the picture i guess the seed dict is updated with false postive words,
so can you explain what's the meaning of this picture?
![image](https://user-images.githubusercontent.com/11830865/34186895-53707a70-e569-11e7-95f8-836177b0fc0e.png)

**Comment by hitxujian** [comment]
![Uploading image.png…]()

**Comment by ryosukee** [comment]
@hitxujian
Sorry for the late reply.

Thank you for pointing it out.
That's true. The seed dict is updated with false positive words.
However, the scripts of this repository are corresponding to below paper.
http://cl.sd.tmu.ac.jp/~miyazaki/publish/nlp2015_miyazaki_paper.pdf
In this paper, the seed dict is not updated.

if you want to conduct experiment again from "nlp2015_miyazaki_poster.pdf", please implement seed updating phase.
it is not complicated process. it can be done by simply adding the words predicted as false positive at the previous step.

Pseudocode:
```
for i in iterate_num:
  traning_set = make_training_set(corpus, dict)
  model = train(training_set)
  result = predict(model, another_corpus)
  fp_words = get_false_positive(result)
  dict += fp_words
```
